baseURL = "https://sheety.vacode.xyz/"
languageCode = "en-us"
defaultContentLanguage = "en"
author = "vaibhavgeek"
title = "Sheety Bot!"
theme = "hugo-vitae"
paginate = 5
enableRobotsTXT = true

copyright = "© Copyright ChaturBots AI Private Limited | Sheety Bots"

pygmentsstyle = "colorful"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

googleAnalytics = ""

[taxonomies]
	tag = "tags"
	category = "categories"
	series = "series"

[params]
	# Use homepage.md instead of a list of posts
	homepage = true

	# Add meta keywords in head part (Site Keywords or Tags of Page)
	keywords = ["vaibhav","google sheets","chatbot","sheetybot"]

	# Add meta description in head part
	description = "Convert your Google Sheets into a chatbot"

	# Add pagetitle to homepage <title> tag
	pagetitle = "Sheety Habit Bots"

	# Add a subtitle to your website
	subtitle = "Convert your Google Sheets into a Chatbot!"

	# Activate to show authors on pages if available
	#listAuthor = true

	# Add math typesetting with KaTeX (Global with this Param)
	math = true

	# Optional 80x80 avatar image.
	avatar = "https://raw.githubusercontent.com/vaibhavgeek/chaturbots/master/app/assets/images/cb_white_blue.png"

	# Optional favicons for website
	#favicon = true

	# Add list of sections that should show up on the homepage
        mainSections = ["post"]

	# Add list of Sections/Types that should no be considered by RSS
	#nofeedSections = ["post"]

	# Deactivate Taxonomies for specific page types
	#disableTaxoTypes = [""]

	# Custom CSS applied to default styles. (Path could be "static/css/")
	#customCSS = "css/custom.css"

# Comments
[params.comments]
# Enable Comments with "true"
enabled = false

# Comment provider:
#   disqus (https://disqus.com)
#   commento (https://commento.io)
#engine = "disqus"

# Content types to disable comments on.
#disableOnTypes = ["page"]

[params.comments.disqus]
#shortname = "" # Paste the shortname from your Disqus dashboard.

[params.comments.commento]
#host = "" # Paste the domain of you commento.io system

# Navigation
[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "About"
url = "/about"
weight = 2

[[menu.main]]
name = "Tutorial"
url = "/tutorial"
weight = 3

[[menu.main]]
name = "Author"
url = "https://vacode.xyz/"
weight = 4


# Social Menu
[[params.social]]
name = "Github"
icon = "fab fa-github"
url = "https://github.com/vaibhavgeek/sheetyBot"

[[params.social]]
name = "Twitter"
icon = "fab fa-twitter"
url = "https://twitter.com/vaibhavgeek"

[[params.social]]
name = "Email"
icon = "fas fa-envelope"
cmd = "mailto:vaibhav.dkm@gmail.com"
